#pragma config(Sensor, in2,    lift,           sensorPotentiometer)
#pragma config(Sensor, in3,    mobile,         sensorPotentiometer)
#pragma config(Sensor, in4,    test,           sensorPotentiometer)
#pragma config(Sensor, in5,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl10, jumper,         sensorDigitalIn)
#pragma config(Motor,  port1,           motorRightEnc, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           motorRightY,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           fourbar,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           motorLeftY,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motorLeftEnc,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "lcd.h"
#include "function.h"
#include "Pcontrol.h"
#include "auto.h"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  //set_gyro(); 			ENABLE AFTER GYRO CODE
  bLCDBacklight = true;
  bStopTasksBetweenModes = true;
  /*
  SensorType[in5]=sensorNone;
	wait10Msec(10);
	SensorType[in5]=sensorGyro;
	wait10Msec(20);

	SensorScale[in5] = 260;
 //Adjust SensorFullCount to set the "rollover" point. 3600 sets the rollover point to +/-3600
 SensorFullCount[in5] = 3600;

  //startTask(lcdBattery);
*/
  auto_type = 2; // standard, mogo autonomous. 0 is driver skills

  while(bIfiRobotDisabled == 1){
  	auto_type = lcd_select();
  	wait10Msec(50);
  }
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................
	auto_5pt_2cone();
  // Remove this function call once you have "real" code.
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	int left, right, speed_right, thres = 15;
  // User control code here, inside the loop
	startTask(intakeControl);
	startTask(rollerControl);
  while (true)
  {
   	//drive
    if(abs(vexRT[Ch3]) > thres) left = vexRT[Ch3];
		else left = 0;
		if(abs(vexRT[Ch2]) > thres) right = vexRT[Ch2];
		else right = 0;

		speed_right = abs(right) - 0;
		if(right <0) speed_right *= (-1);

		motor[port9] = motor[port10] = left;
		motor[port1] = motor[port2] = speed_right;

    //mogo
    if(vexRT[Btn8U] && !vexRT[Btn8D] && SensorValue[in3] < 3885){
    	/*if(SensorValue[dgtl10])*/ motor[port8] = 127;
    	//else if(!SensorValue[dgtl10]) mogoUp2();
    }
    else if(vexRT[Btn8D] && !vexRT[Btn8U] && SensorValue[in3] > 1050){
    	/*if(SensorValue[dgtl10])*/ motor[port8]=-127;
    //	else if(!SensorValue[dgtl10]) mogoDown2();
    }
    else motor[port8] = 0;

    // lift
    if(vexRT[Btn5U]) motor[port3]=motor[port4]=127;
    else if(vexRT[Btn5D]) motor[port3]=motor[port4]=-127;
    else{
    	if(SensorValue[dgtl10])motor[port3]=motor[port4]=0;
    	else motor[port4]=motor[port3]=8;
    }

    //fourbar
    /*
    if(vexRT[Btn6U]) motor[port7] = 127;
    else if(vexRT[Btn6D]) motor[port7]=-127;
    else motor[port7]=0;*/

    // test

    //if(vexRT[Btn7U]) mogoUp();
    //if(vexRT[Btn7D]) mogoDown();
    if(vexRT[Btn7L]) skills();
    //if(vexRT[Btn7R]) auto_20pt_2cone();

		displayLCDNumber(0,0, SensorValue[in5]);
		displayLCDNumber(1,0, SensorValue[in2]);
  }
}
